# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mddarr/aptitude/data_structures/template_data_structures

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mddarr/aptitude/data_structures/template_data_structures

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mddarr/aptitude/data_structures/template_data_structures/CMakeFiles /home/mddarr/aptitude/data_structures/template_data_structures/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mddarr/aptitude/data_structures/template_data_structures/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named good_vector

# Build rule for target.
good_vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 good_vector
.PHONY : good_vector

# fast build rule for target.
good_vector/fast:
	$(MAKE) -f CMakeFiles/good_vector.dir/build.make CMakeFiles/good_vector.dir/build
.PHONY : good_vector/fast

#=============================================================================
# Target rules for targets named vector

# Build rule for target.
vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vector
.PHONY : vector

# fast build rule for target.
vector/fast:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/build
.PHONY : vector/fast

#=============================================================================
# Target rules for targets named dijikstra

# Build rule for target.
dijikstra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dijikstra
.PHONY : dijikstra

# fast build rule for target.
dijikstra/fast:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/build
.PHONY : dijikstra/fast

#=============================================================================
# Target rules for targets named topological_sort

# Build rule for target.
topological_sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 topological_sort
.PHONY : topological_sort

# fast build rule for target.
topological_sort/fast:
	$(MAKE) -f CMakeFiles/topological_sort.dir/build.make CMakeFiles/topological_sort.dir/build
.PHONY : topological_sort/fast

#=============================================================================
# Target rules for targets named color

# Build rule for target.
color: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 color
.PHONY : color

# fast build rule for target.
color/fast:
	$(MAKE) -f CMakeFiles/color.dir/build.make CMakeFiles/color.dir/build
.PHONY : color/fast

#=============================================================================
# Target rules for targets named stack_test

# Build rule for target.
stack_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stack_test
.PHONY : stack_test

# fast build rule for target.
stack_test/fast:
	$(MAKE) -f CMakeFiles/stack_test.dir/build.make CMakeFiles/stack_test.dir/build
.PHONY : stack_test/fast

color.o: color.cpp.o

.PHONY : color.o

# target to build an object file
color.cpp.o:
	$(MAKE) -f CMakeFiles/color.dir/build.make CMakeFiles/color.dir/color.cpp.o
.PHONY : color.cpp.o

color.i: color.cpp.i

.PHONY : color.i

# target to preprocess a source file
color.cpp.i:
	$(MAKE) -f CMakeFiles/color.dir/build.make CMakeFiles/color.dir/color.cpp.i
.PHONY : color.cpp.i

color.s: color.cpp.s

.PHONY : color.s

# target to generate assembly for a file
color.cpp.s:
	$(MAKE) -f CMakeFiles/color.dir/build.make CMakeFiles/color.dir/color.cpp.s
.PHONY : color.cpp.s

dijikstra.o: dijikstra.cpp.o

.PHONY : dijikstra.o

# target to build an object file
dijikstra.cpp.o:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/dijikstra.cpp.o
.PHONY : dijikstra.cpp.o

dijikstra.i: dijikstra.cpp.i

.PHONY : dijikstra.i

# target to preprocess a source file
dijikstra.cpp.i:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/dijikstra.cpp.i
.PHONY : dijikstra.cpp.i

dijikstra.s: dijikstra.cpp.s

.PHONY : dijikstra.s

# target to generate assembly for a file
dijikstra.cpp.s:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/dijikstra.cpp.s
.PHONY : dijikstra.cpp.s

good_vector_test.o: good_vector_test.cpp.o

.PHONY : good_vector_test.o

# target to build an object file
good_vector_test.cpp.o:
	$(MAKE) -f CMakeFiles/good_vector.dir/build.make CMakeFiles/good_vector.dir/good_vector_test.cpp.o
.PHONY : good_vector_test.cpp.o

good_vector_test.i: good_vector_test.cpp.i

.PHONY : good_vector_test.i

# target to preprocess a source file
good_vector_test.cpp.i:
	$(MAKE) -f CMakeFiles/good_vector.dir/build.make CMakeFiles/good_vector.dir/good_vector_test.cpp.i
.PHONY : good_vector_test.cpp.i

good_vector_test.s: good_vector_test.cpp.s

.PHONY : good_vector_test.s

# target to generate assembly for a file
good_vector_test.cpp.s:
	$(MAKE) -f CMakeFiles/good_vector.dir/build.make CMakeFiles/good_vector.dir/good_vector_test.cpp.s
.PHONY : good_vector_test.cpp.s

stack_test.o: stack_test.cpp.o

.PHONY : stack_test.o

# target to build an object file
stack_test.cpp.o:
	$(MAKE) -f CMakeFiles/stack_test.dir/build.make CMakeFiles/stack_test.dir/stack_test.cpp.o
.PHONY : stack_test.cpp.o

stack_test.i: stack_test.cpp.i

.PHONY : stack_test.i

# target to preprocess a source file
stack_test.cpp.i:
	$(MAKE) -f CMakeFiles/stack_test.dir/build.make CMakeFiles/stack_test.dir/stack_test.cpp.i
.PHONY : stack_test.cpp.i

stack_test.s: stack_test.cpp.s

.PHONY : stack_test.s

# target to generate assembly for a file
stack_test.cpp.s:
	$(MAKE) -f CMakeFiles/stack_test.dir/build.make CMakeFiles/stack_test.dir/stack_test.cpp.s
.PHONY : stack_test.cpp.s

topological_sort.o: topological_sort.cpp.o

.PHONY : topological_sort.o

# target to build an object file
topological_sort.cpp.o:
	$(MAKE) -f CMakeFiles/topological_sort.dir/build.make CMakeFiles/topological_sort.dir/topological_sort.cpp.o
.PHONY : topological_sort.cpp.o

topological_sort.i: topological_sort.cpp.i

.PHONY : topological_sort.i

# target to preprocess a source file
topological_sort.cpp.i:
	$(MAKE) -f CMakeFiles/topological_sort.dir/build.make CMakeFiles/topological_sort.dir/topological_sort.cpp.i
.PHONY : topological_sort.cpp.i

topological_sort.s: topological_sort.cpp.s

.PHONY : topological_sort.s

# target to generate assembly for a file
topological_sort.cpp.s:
	$(MAKE) -f CMakeFiles/topological_sort.dir/build.make CMakeFiles/topological_sort.dir/topological_sort.cpp.s
.PHONY : topological_sort.cpp.s

vector_test.o: vector_test.cpp.o

.PHONY : vector_test.o

# target to build an object file
vector_test.cpp.o:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/vector_test.cpp.o
.PHONY : vector_test.cpp.o

vector_test.i: vector_test.cpp.i

.PHONY : vector_test.i

# target to preprocess a source file
vector_test.cpp.i:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/vector_test.cpp.i
.PHONY : vector_test.cpp.i

vector_test.s: vector_test.cpp.s

.PHONY : vector_test.s

# target to generate assembly for a file
vector_test.cpp.s:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/vector_test.cpp.s
.PHONY : vector_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... good_vector"
	@echo "... vector"
	@echo "... dijikstra"
	@echo "... topological_sort"
	@echo "... color"
	@echo "... stack_test"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... dijikstra.o"
	@echo "... dijikstra.i"
	@echo "... dijikstra.s"
	@echo "... good_vector_test.o"
	@echo "... good_vector_test.i"
	@echo "... good_vector_test.s"
	@echo "... stack_test.o"
	@echo "... stack_test.i"
	@echo "... stack_test.s"
	@echo "... topological_sort.o"
	@echo "... topological_sort.i"
	@echo "... topological_sort.s"
	@echo "... vector_test.o"
	@echo "... vector_test.i"
	@echo "... vector_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

