# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mddarr/aptitude/data_structures/template_data_structures

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mddarr/aptitude/data_structures/template_data_structures

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mddarr/aptitude/data_structures/template_data_structures/CMakeFiles /home/mddarr/aptitude/data_structures/template_data_structures/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mddarr/aptitude/data_structures/template_data_structures/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named heap

# Build rule for target.
heap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heap
.PHONY : heap

# fast build rule for target.
heap/fast:
	$(MAKE) -f CMakeFiles/heap.dir/build.make CMakeFiles/heap.dir/build
.PHONY : heap/fast

#=============================================================================
# Target rules for targets named graph

# Build rule for target.
graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph
.PHONY : graph

# fast build rule for target.
graph/fast:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/build
.PHONY : graph/fast

#=============================================================================
# Target rules for targets named adj_list

# Build rule for target.
adj_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adj_list
.PHONY : adj_list

# fast build rule for target.
adj_list/fast:
	$(MAKE) -f CMakeFiles/adj_list.dir/build.make CMakeFiles/adj_list.dir/build
.PHONY : adj_list/fast

#=============================================================================
# Target rules for targets named linked_list

# Build rule for target.
linked_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linked_list
.PHONY : linked_list

# fast build rule for target.
linked_list/fast:
	$(MAKE) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/build
.PHONY : linked_list/fast

#=============================================================================
# Target rules for targets named dijikstra

# Build rule for target.
dijikstra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dijikstra
.PHONY : dijikstra

# fast build rule for target.
dijikstra/fast:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/build
.PHONY : dijikstra/fast

#=============================================================================
# Target rules for targets named prim

# Build rule for target.
prim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prim
.PHONY : prim

# fast build rule for target.
prim/fast:
	$(MAKE) -f CMakeFiles/prim.dir/build.make CMakeFiles/prim.dir/build
.PHONY : prim/fast

#=============================================================================
# Target rules for targets named binary_tree

# Build rule for target.
binary_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binary_tree
.PHONY : binary_tree

# fast build rule for target.
binary_tree/fast:
	$(MAKE) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/build
.PHONY : binary_tree/fast

#=============================================================================
# Target rules for targets named adj_matrix

# Build rule for target.
adj_matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adj_matrix
.PHONY : adj_matrix

# fast build rule for target.
adj_matrix/fast:
	$(MAKE) -f CMakeFiles/adj_matrix.dir/build.make CMakeFiles/adj_matrix.dir/build
.PHONY : adj_matrix/fast

#=============================================================================
# Target rules for targets named kruskall

# Build rule for target.
kruskall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kruskall
.PHONY : kruskall

# fast build rule for target.
kruskall/fast:
	$(MAKE) -f CMakeFiles/kruskall.dir/build.make CMakeFiles/kruskall.dir/build
.PHONY : kruskall/fast

#=============================================================================
# Target rules for targets named dijikstra_adjlist

# Build rule for target.
dijikstra_adjlist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dijikstra_adjlist
.PHONY : dijikstra_adjlist

# fast build rule for target.
dijikstra_adjlist/fast:
	$(MAKE) -f CMakeFiles/dijikstra_adjlist.dir/build.make CMakeFiles/dijikstra_adjlist.dir/build
.PHONY : dijikstra_adjlist/fast

adj_list_test.o: adj_list_test.cpp.o

.PHONY : adj_list_test.o

# target to build an object file
adj_list_test.cpp.o:
	$(MAKE) -f CMakeFiles/adj_list.dir/build.make CMakeFiles/adj_list.dir/adj_list_test.cpp.o
.PHONY : adj_list_test.cpp.o

adj_list_test.i: adj_list_test.cpp.i

.PHONY : adj_list_test.i

# target to preprocess a source file
adj_list_test.cpp.i:
	$(MAKE) -f CMakeFiles/adj_list.dir/build.make CMakeFiles/adj_list.dir/adj_list_test.cpp.i
.PHONY : adj_list_test.cpp.i

adj_list_test.s: adj_list_test.cpp.s

.PHONY : adj_list_test.s

# target to generate assembly for a file
adj_list_test.cpp.s:
	$(MAKE) -f CMakeFiles/adj_list.dir/build.make CMakeFiles/adj_list.dir/adj_list_test.cpp.s
.PHONY : adj_list_test.cpp.s

adj_matrix_test.o: adj_matrix_test.cpp.o

.PHONY : adj_matrix_test.o

# target to build an object file
adj_matrix_test.cpp.o:
	$(MAKE) -f CMakeFiles/adj_matrix.dir/build.make CMakeFiles/adj_matrix.dir/adj_matrix_test.cpp.o
.PHONY : adj_matrix_test.cpp.o

adj_matrix_test.i: adj_matrix_test.cpp.i

.PHONY : adj_matrix_test.i

# target to preprocess a source file
adj_matrix_test.cpp.i:
	$(MAKE) -f CMakeFiles/adj_matrix.dir/build.make CMakeFiles/adj_matrix.dir/adj_matrix_test.cpp.i
.PHONY : adj_matrix_test.cpp.i

adj_matrix_test.s: adj_matrix_test.cpp.s

.PHONY : adj_matrix_test.s

# target to generate assembly for a file
adj_matrix_test.cpp.s:
	$(MAKE) -f CMakeFiles/adj_matrix.dir/build.make CMakeFiles/adj_matrix.dir/adj_matrix_test.cpp.s
.PHONY : adj_matrix_test.cpp.s

binary_tree_test.o: binary_tree_test.cpp.o

.PHONY : binary_tree_test.o

# target to build an object file
binary_tree_test.cpp.o:
	$(MAKE) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/binary_tree_test.cpp.o
.PHONY : binary_tree_test.cpp.o

binary_tree_test.i: binary_tree_test.cpp.i

.PHONY : binary_tree_test.i

# target to preprocess a source file
binary_tree_test.cpp.i:
	$(MAKE) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/binary_tree_test.cpp.i
.PHONY : binary_tree_test.cpp.i

binary_tree_test.s: binary_tree_test.cpp.s

.PHONY : binary_tree_test.s

# target to generate assembly for a file
binary_tree_test.cpp.s:
	$(MAKE) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/binary_tree_test.cpp.s
.PHONY : binary_tree_test.cpp.s

dijikstra.o: dijikstra.cpp.o

.PHONY : dijikstra.o

# target to build an object file
dijikstra.cpp.o:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/dijikstra.cpp.o
.PHONY : dijikstra.cpp.o

dijikstra.i: dijikstra.cpp.i

.PHONY : dijikstra.i

# target to preprocess a source file
dijikstra.cpp.i:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/dijikstra.cpp.i
.PHONY : dijikstra.cpp.i

dijikstra.s: dijikstra.cpp.s

.PHONY : dijikstra.s

# target to generate assembly for a file
dijikstra.cpp.s:
	$(MAKE) -f CMakeFiles/dijikstra.dir/build.make CMakeFiles/dijikstra.dir/dijikstra.cpp.s
.PHONY : dijikstra.cpp.s

dijikstra_adjlist.o: dijikstra_adjlist.cpp.o

.PHONY : dijikstra_adjlist.o

# target to build an object file
dijikstra_adjlist.cpp.o:
	$(MAKE) -f CMakeFiles/dijikstra_adjlist.dir/build.make CMakeFiles/dijikstra_adjlist.dir/dijikstra_adjlist.cpp.o
.PHONY : dijikstra_adjlist.cpp.o

dijikstra_adjlist.i: dijikstra_adjlist.cpp.i

.PHONY : dijikstra_adjlist.i

# target to preprocess a source file
dijikstra_adjlist.cpp.i:
	$(MAKE) -f CMakeFiles/dijikstra_adjlist.dir/build.make CMakeFiles/dijikstra_adjlist.dir/dijikstra_adjlist.cpp.i
.PHONY : dijikstra_adjlist.cpp.i

dijikstra_adjlist.s: dijikstra_adjlist.cpp.s

.PHONY : dijikstra_adjlist.s

# target to generate assembly for a file
dijikstra_adjlist.cpp.s:
	$(MAKE) -f CMakeFiles/dijikstra_adjlist.dir/build.make CMakeFiles/dijikstra_adjlist.dir/dijikstra_adjlist.cpp.s
.PHONY : dijikstra_adjlist.cpp.s

graph_test.o: graph_test.cpp.o

.PHONY : graph_test.o

# target to build an object file
graph_test.cpp.o:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/graph_test.cpp.o
.PHONY : graph_test.cpp.o

graph_test.i: graph_test.cpp.i

.PHONY : graph_test.i

# target to preprocess a source file
graph_test.cpp.i:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/graph_test.cpp.i
.PHONY : graph_test.cpp.i

graph_test.s: graph_test.cpp.s

.PHONY : graph_test.s

# target to generate assembly for a file
graph_test.cpp.s:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/graph_test.cpp.s
.PHONY : graph_test.cpp.s

heap_test.o: heap_test.cpp.o

.PHONY : heap_test.o

# target to build an object file
heap_test.cpp.o:
	$(MAKE) -f CMakeFiles/heap.dir/build.make CMakeFiles/heap.dir/heap_test.cpp.o
.PHONY : heap_test.cpp.o

heap_test.i: heap_test.cpp.i

.PHONY : heap_test.i

# target to preprocess a source file
heap_test.cpp.i:
	$(MAKE) -f CMakeFiles/heap.dir/build.make CMakeFiles/heap.dir/heap_test.cpp.i
.PHONY : heap_test.cpp.i

heap_test.s: heap_test.cpp.s

.PHONY : heap_test.s

# target to generate assembly for a file
heap_test.cpp.s:
	$(MAKE) -f CMakeFiles/heap.dir/build.make CMakeFiles/heap.dir/heap_test.cpp.s
.PHONY : heap_test.cpp.s

kruskall.o: kruskall.cpp.o

.PHONY : kruskall.o

# target to build an object file
kruskall.cpp.o:
	$(MAKE) -f CMakeFiles/kruskall.dir/build.make CMakeFiles/kruskall.dir/kruskall.cpp.o
.PHONY : kruskall.cpp.o

kruskall.i: kruskall.cpp.i

.PHONY : kruskall.i

# target to preprocess a source file
kruskall.cpp.i:
	$(MAKE) -f CMakeFiles/kruskall.dir/build.make CMakeFiles/kruskall.dir/kruskall.cpp.i
.PHONY : kruskall.cpp.i

kruskall.s: kruskall.cpp.s

.PHONY : kruskall.s

# target to generate assembly for a file
kruskall.cpp.s:
	$(MAKE) -f CMakeFiles/kruskall.dir/build.make CMakeFiles/kruskall.dir/kruskall.cpp.s
.PHONY : kruskall.cpp.s

linked_list_test.o: linked_list_test.cpp.o

.PHONY : linked_list_test.o

# target to build an object file
linked_list_test.cpp.o:
	$(MAKE) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/linked_list_test.cpp.o
.PHONY : linked_list_test.cpp.o

linked_list_test.i: linked_list_test.cpp.i

.PHONY : linked_list_test.i

# target to preprocess a source file
linked_list_test.cpp.i:
	$(MAKE) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/linked_list_test.cpp.i
.PHONY : linked_list_test.cpp.i

linked_list_test.s: linked_list_test.cpp.s

.PHONY : linked_list_test.s

# target to generate assembly for a file
linked_list_test.cpp.s:
	$(MAKE) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/linked_list_test.cpp.s
.PHONY : linked_list_test.cpp.s

prim.o: prim.cpp.o

.PHONY : prim.o

# target to build an object file
prim.cpp.o:
	$(MAKE) -f CMakeFiles/prim.dir/build.make CMakeFiles/prim.dir/prim.cpp.o
.PHONY : prim.cpp.o

prim.i: prim.cpp.i

.PHONY : prim.i

# target to preprocess a source file
prim.cpp.i:
	$(MAKE) -f CMakeFiles/prim.dir/build.make CMakeFiles/prim.dir/prim.cpp.i
.PHONY : prim.cpp.i

prim.s: prim.cpp.s

.PHONY : prim.s

# target to generate assembly for a file
prim.cpp.s:
	$(MAKE) -f CMakeFiles/prim.dir/build.make CMakeFiles/prim.dir/prim.cpp.s
.PHONY : prim.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... heap"
	@echo "... graph"
	@echo "... adj_list"
	@echo "... linked_list"
	@echo "... dijikstra"
	@echo "... edit_cache"
	@echo "... prim"
	@echo "... binary_tree"
	@echo "... adj_matrix"
	@echo "... kruskall"
	@echo "... dijikstra_adjlist"
	@echo "... adj_list_test.o"
	@echo "... adj_list_test.i"
	@echo "... adj_list_test.s"
	@echo "... adj_matrix_test.o"
	@echo "... adj_matrix_test.i"
	@echo "... adj_matrix_test.s"
	@echo "... binary_tree_test.o"
	@echo "... binary_tree_test.i"
	@echo "... binary_tree_test.s"
	@echo "... dijikstra.o"
	@echo "... dijikstra.i"
	@echo "... dijikstra.s"
	@echo "... dijikstra_adjlist.o"
	@echo "... dijikstra_adjlist.i"
	@echo "... dijikstra_adjlist.s"
	@echo "... graph_test.o"
	@echo "... graph_test.i"
	@echo "... graph_test.s"
	@echo "... heap_test.o"
	@echo "... heap_test.i"
	@echo "... heap_test.s"
	@echo "... kruskall.o"
	@echo "... kruskall.i"
	@echo "... kruskall.s"
	@echo "... linked_list_test.o"
	@echo "... linked_list_test.i"
	@echo "... linked_list_test.s"
	@echo "... prim.o"
	@echo "... prim.i"
	@echo "... prim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

